name: CI

on:
  # schedule:
  #   - cron: '5 4 * * *'

  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:     

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Install mdbook
      run: brew install mdbook

    - name: Report versions
      run: |
        mdbook --version

    - name: Build HTML
      run: mdbook build

    - name: Publish book
      run: |
        git config --global init.defaultBranch main
        git config --global url."https://".insteadOf git://
        git config --global url."$GITHUB_SERVER_URL/".insteadOf "git@github.com":

        remote_repo="https://${TOKEN}@github.com/marionegroponzi/snippets.git"

        cd book
        git init
        git config user.name "GitHub Actions"
        git config user.email "github-actions-bot@users.noreply.github.com"
        rm -f .DS_Store
        git add .

        git commit -m "Deploy snippets to snippets:docs"
        git push --force "${remote_repo}" main:docs

      env:
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}
