name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Install mdbook
      run: brew install mdbook

    - name: Report versions
      run: |
        mdbook --version

    - name: Build HTML
      run: mdbook build

    - name: Publish book
      run: |
        git log
        ls
      env:
        # Target branch
        PAGES_BRANCH: docs
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}